apiVersion: v1
kind: ConfigMap
metadata:
 namespace: metallb-system
 name: config
data:
 config: |
 peers:
 - peer-address: 10.0.0.2
 peer-asn: 100
 my-asn: 42
 address-pools:
 - name: default
 cidr:
 - 192.168.49.0/24
 advertisements:
 - aggregation-length: 32
