apiVersion: v1
kind: Service
metadata:
  name: mysql
  annotations:
    metallb.universe.tf/allow-shared-ip: 192.168.49.3-192.168.49.3
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - name: http
      port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: image-mysql
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
