apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: 192.168.49.2-192.168.49.2
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - name: http
      port: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: image-wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
        livenessProbe:
          exec:
            command:
            - curl
            - -I
            - http://localhost:5050
      restartPolicy: Always