apiVersion: v1
kind: Service
metadata:
  name: vsftpd
  annotations:
    metallb.universe.tf/allow-shared-ip: 192.168.49.3-192.168.49.3
spec:
  type: LoadBalancer
  selector:
    app: vsftpd
  ports:
    - name: connection
      port: 21
      nodePort: 30021
    - name: datatransfer
      port: 20
      nodePort: 30020
    - name: user1
      port: 30000
      nodePort: 30022
    - name: user2
      port: 30001
      nodePort: 30023
    - name: user3
      port: 30002
      nodePort: 30024
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsftpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vsftpd
  template:
    metadata:
      labels:
        app: vsftpd
    spec:
      containers:
      - name: vsftpd
        image: image-vsftpd
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 20
        - containerPort: 30000
        - containerPort: 30001
        - containerPort: 30002
