apiVersion: v1
kind: Service
metadata:
  name: vsftpd
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 21
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsftpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vsftpd
  template:
    metadata:
      labels:
        app: vsftpd
    spec:
      containers:
      - name: vsftpd
        image: image-vsftpd
        imagePullPolicy: Never
        ports:
        - containerPort: 21
