apiVersion: v1
kind: Service
metadata:
  name: vsftpd
  annotations:
    metallb.universe.tf/allow-shared-ip: 192.168.49.2-192.168.49.2
spec:
  type: LoadBalancer
  selector:
    app: vsftpd
  ports:
    - name: connection
      port: 21
      nodePort: 30021
    - name: datatransfer
      port: 30020
      nodePort: 30022
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vsftpd-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: vsftpd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsftpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vsftpd
  template:
    metadata:
      labels:
        app: vsftpd
    spec:
      containers:
      - name: vsftpd
        image: image-vsftpd
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 30020
        volumeMounts:
        - name: vsftpd-pvs
          mountPath: /etc/vsftpd/
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - 'ps aux | grep vsftpd'
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always
      volumes:
      - name: vsftpd-pvs
        persistentVolumeClaim:
          claimName: vsftpd-pvc
