apiVersion: v1
kind: Service
metadata:
  name: vsftpd
  annotations:
    metallb.universe.tf/allow-shared-ip: 192.168.49.3-192.168.49.3
spec:
  type: LoadBalancer
  selector:
    app: vsftpd
  ports:
    - name: connection
      port: 21
    - name: datatransfer
      port: 20
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsftpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vsftpd
  template:
    metadata:
      labels:
        app: vsftpd
    spec:
      containers:
      - name: vsftpd
        image: image-vsftpd
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 20
